### ISSUE TITLE
How to insert and update data

### ISSUE THREAD

**Issue by clockworkdrive13** [vbilopav/NoOrm.Net#2]
Your norm.net looks great and is working well for query.

Is Insert/update data supported as well, if yes, can you provide an example

Thanks.

**Comment by vbilopav** [comment]
Of course, you can execute any custom SQL, that's the whole point.

Basically you can use execute since Insert/update doesn't return any results -> see [execute unit tests](https://github.com/vbilopav/NoOrm.Net/blob/master/Tests/PostgreSqlUnitTests/ExecuteUnitTests.cs)

If you using Insert/update that returns some rows (by returning clause) then u can use Single to execute insert and fetch single result of the insert operation.
