### ISSUE TITLE
SelectAwait not working in .net core 3.1

### ISSUE THREAD

**Issue by ben1628** [vbilopav/NoOrm.Net#3]
the sample app used to work with .SelectAwait. After upgrading the .net core to 3.1, SelectAwait is no longer resolved, and using system.linq is grayed out meaning it's not used.

Any idea?

**Comment by vbilopav** [comment]
Yes. You've probably upgraded Norm to a higher version. 

In version 1.1.6 I removed `System.Linq.Async` since it is not really necessary. See the changelog:
https://github.com/vbilopav/NoOrm.Net/blob/master/CHANGES.md#116

You may, however, add manually NuGet `System.Linq.Async` to your project and it will work again.
