### ISSUE TITLE
transaction with mutiple execute command ??

### ISSUE THREAD

**Issue by ductai230894** [vbilopav/NoOrm.Net#5]
Hello sir,
I don't see how to use transaction with execute command?
Can you help me ?

I think it is better to have a transaction with multi execute command;

**Comment by vbilopav** [comment]
Sure, I just wrote an article about that. It is aimed to PostgreSQL database, but some things could apply, you can check it out here: <https://dev.to/vbilopav/postgresql-enhancements-in-norm-net-3g4b>

You can do the following:

```chsharp
var tran = connection.BeginTransaction();
try
{
    connection
        .Execute("command 1")
        .Execute("command 2");
        // etc...

    tran.Commit();
}
catch (Exception e)
{
    tran.Rollback();
    _logger.Error(e);                
}
```

But, I, personally, like to send one, single command to the server, instead of four, just to minimize network latency:

```chsharp
try
{
    connection.Execute(@"

        begin;
           command 1;
           command 2;
           -- etc
        end;
    ");
}
catch (Exception e)
{
    connection.Execute("rollback");
    _logger.Error(e);                
}
```

That would work with PostgreSQL and probably with other providers as well, but I'd have to check it out.

There are some other issues with this approach on PostgreSQL specifically you can check it out in my article above...

Hope this helps.
